spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banking
    username: root
    password: Ms4life!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Automatically creates or updates tables based on your entities
    show-sql: true  # Shows generated SQL in the console
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL 8 dialect for Hibernate
